title: 기술노트
description: Blogging about technical stuffs
meta_description: "Blogging about stuffs, python, code, IT."

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
url: https://it.kblck.com
baseurl: /
domain_name: https://it.kblck.com
google_analytics: "UA-XXXXXXXX-X"
plugins: 
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed  

# Details for the RSS feed generator
url: ""
author: "Benny"

# Disqus config
disqus-shortname: ""
